export const tagsList = [
	'Brexit',
	'Environment',
	'Climate Change',
	'Energy',
	'Public Health',
	'Food Safety',
	'Agriculture',
	'Rural Development',
	'Fisheries',
	'Maritime Affairs',
	'Digital',
	'Data Protection',
	'Technology',
	'Cybersecurity',
	'Research Innovation',
	'Education',
	'Culture',
	'Employment',
	'Social Affairs',
	'Legal Affairs',
	'Civil Liberties',
	'Constitutional Affairs',
	'Justice and Home Affairs',
	'Budgets',
	'Budgetary Control',
	'Financial Crimes',
	'Tax Avoidance',
	'Migration',
	'Human Rights',
	'Development',
	'Security and Defense',
	'Foreign Affairs',
	'International Trade',
	'Internal Market',
	'Consumer Protection',
	'Industry',
	'Competition',
	'Regional Development',
	'Transport',
	'Tourism',
	'Urban Development'
];
